#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ROOT_DIR=$(cd "$SCRIPT_DIR/.." && pwd)
TOOLS_DIR="$ROOT_DIR/.tools"

if ! command -v curl >/dev/null 2>&1; then
  echo "Missing tool: curl"
  exit 1
fi
if ! command -v tar >/dev/null 2>&1; then
  echo "Missing tool: tar"
  exit 1
fi
if ! command -v unzip >/dev/null 2>&1; then
  echo "Missing tool: unzip"
  exit 1
fi

mkdir -p "$TOOLS_DIR"

OS=$(uname -s)
ARCH=$(uname -m)

JDK_VERSION="21.0.4+7"
JDK_ARCHIVE=""

if [[ "$OS" == "Darwin" ]]; then
  if [[ "$ARCH" == "arm64" ]]; then
    JDK_ARCHIVE="OpenJDK21U-jdk_aarch64_mac_hotspot_21.0.4_7.tar.gz"
  elif [[ "$ARCH" == "x86_64" ]]; then
    JDK_ARCHIVE="OpenJDK21U-jdk_x64_mac_hotspot_21.0.4_7.tar.gz"
  else
    echo "Unsupported architecture: $ARCH"
    exit 1
  fi
elif [[ "$OS" == "Linux" ]]; then
  if [[ "$ARCH" == "aarch64" || "$ARCH" == "arm64" ]]; then
    JDK_ARCHIVE="OpenJDK21U-jdk_aarch64_linux_hotspot_21.0.4_7.tar.gz"
  elif [[ "$ARCH" == "x86_64" ]]; then
    JDK_ARCHIVE="OpenJDK21U-jdk_x64_linux_hotspot_21.0.4_7.tar.gz"
  else
    echo "Unsupported architecture: $ARCH"
    exit 1
  fi
else
  echo "Unsupported OS: $OS"
  exit 1
fi

JDK_URL="https://github.com/adoptium/temurin21-binaries/releases/download/jdk-${JDK_VERSION}/${JDK_ARCHIVE}"
JDK_DIR="$TOOLS_DIR/jdk-21"

if [[ ! -d "$JDK_DIR" ]]; then
  echo "Downloading JDK 21 from: $JDK_URL"
  JDK_TAR="$TOOLS_DIR/jdk-21.tar.gz"
  curl -L -o "$JDK_TAR" "$JDK_URL"
  JDK_ROOT=$(tar -tzf "$JDK_TAR" | head -n 1 | cut -d/ -f1)
  tar -xzf "$JDK_TAR" -C "$TOOLS_DIR"
  rm -f "$JDK_TAR"
  if [[ -z "$JDK_ROOT" || ! -d "$TOOLS_DIR/$JDK_ROOT" ]]; then
    echo "Failed to locate extracted JDK directory."
    exit 1
  fi
  mv "$TOOLS_DIR/$JDK_ROOT" "$JDK_DIR"
fi

if [[ -d "$JDK_DIR/Contents/Home" ]]; then
  JAVA_HOME_PATH="$JDK_DIR/Contents/Home"
else
  JAVA_HOME_PATH="$JDK_DIR"
fi

GRADLE_VERSION="8.8"
GRADLE_URL="https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip"
GRADLE_DIR="$TOOLS_DIR/gradle-${GRADLE_VERSION}"

if [[ ! -d "$GRADLE_DIR" ]]; then
  echo "Downloading Gradle $GRADLE_VERSION from: $GRADLE_URL"
  GRADLE_ZIP="$TOOLS_DIR/gradle-${GRADLE_VERSION}.zip"
  curl -L -o "$GRADLE_ZIP" "$GRADLE_URL"
  unzip -q "$GRADLE_ZIP" -d "$TOOLS_DIR"
  rm -f "$GRADLE_ZIP"
fi

ENV_FILE="$ROOT_DIR/.env"
cat > "$ENV_FILE" <<ENV_VARS
# Generated by scripts/setup-env.sh
JAVA_HOME=$JAVA_HOME_PATH
GRADLE_HOME=$GRADLE_DIR
GRADLE_BIN=$GRADLE_DIR/bin/gradle
ENV_VARS

if [[ -n "${HTTP_PROXY:-}" ]]; then
  echo "HTTP_PROXY=$HTTP_PROXY" >> "$ENV_FILE"
fi
if [[ -n "${HTTPS_PROXY:-}" ]]; then
  echo "HTTPS_PROXY=$HTTPS_PROXY" >> "$ENV_FILE"
fi
if [[ -n "${NO_PROXY:-}" ]]; then
  echo "NO_PROXY=$NO_PROXY" >> "$ENV_FILE"
fi

echo "Wrote $ENV_FILE"
echo "Run: $ROOT_DIR/scripts/build-plugin.sh"
